### ISSUE TITLE
UMTRANSACTION has a deprecated constructor 

### ISSUE THREAD

**Issue by jamestochhub** [proexchange/com.pesc.usaepay#13]
Keep getting this error in my logs. 

> Methods with the same name as their class will not be constructors in a future version of PHP; umTransaction has a deprecated constructor
    [file] => /public_html/wp-content/uploads/civicrm/ext/com.pesc.usaepay/packages/usaepay-php/usaepay.php
    [line] => 16

**Comment by mark-rodgers** [comment]
This is an issue with the USAePay PHP Library. They haven't updated their library since 2016. A user on GitHub made a pull request 2 years ago to fix the issue on the upstream, which went unnoticed, so I'm going to say it's safe to assume they are no longer maintaining the library. I've gone ahead and manually patched this in our extension to prevent it from throwing exceptions in PHP 7.1+ :beers: 

https://github.com/usaepay/usaepay-php/issues/8
